apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity
  template:
    metadata:
      labels:
        app: activity
    spec:
      containers:
        - name: activity
          image: phobopt/activity
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: 'orders'
            - name: MONGO_URI
              value: mongodb://activity-mongo-srv:27017/activity
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: activity-srv
spec:
  selector:
    app: activity
  ports:
    - name: activity
      protocol: TCP
      port: 3000
      targetPort: 3000