apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
        - name: report
          image: phobopt/report
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: 'orders'
            - name: MONGO_URI
              value: mongodb://report-mongo-srv:27017/report
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: report-srv
spec:
  selector:
    app: report
  ports:
    - name: report
      protocol: TCP
      port: 3000
      targetPort: 3000